LAMBDAS:
  MASK: 0.3
  PERC:
  - 0.01
  - 0.05
  - 0.0
  - 0.01
LOG:
  LOSSES: true
  SAVE_ITER: 4000
LR:
  BETAS:
  - 0.5
  - 0.999
  LR: 0.0002
MODEL:
  DISC: linear
  INIT_GAIN: 0.03
  INIT_TYPE: orthogonal
  LATENT_SZ: 32
  NDF: 32
  NGF: 32
  N_CLASSES: 10
MODEL_NAME: tmp
TRAIN:
  BATCH_SIZE: 64
  COLOR_VAR: 0.02
  DATASET: cifar10
  EPOCHS: 60
  WORKERS: 12
