LAMBDAS:
  MASK: 0.003
  PERC:
  - 0.01
  - 0.05
  - 0.0
  - 0.01
LOG:
  LOSSES: true
  SAVE_ITER: 10000
LR:
  BETAS:
  - 0.5
  - 0.999
  LR: 0.0002
MODEL:
  DISC: conv
  INIT_GAIN: 0.03
  INIT_TYPE: normal
  LATENT_SZ: 32
  NDF: 64
  NGF: 64
  N_CLASSES: 1
MODEL_NAME: tmp
TRAIN:
  BATCH_SIZE: 64
  COLOR_VAR: 0.02
  DATASET: svhn2
  EPOCHS: 30
  WORKERS: 12
